### ISSUE TITLE
[iOS][Android] RNCNetInfo.getCurrentState was called with 1 arguments but expected 0 arguments

### ISSUE THREAD

**Issue by imtalwindersingh** [rgommezz/react-native-offline#252]
### Current Behavior

When I tried to wrap my child components with the ReduxNetworkProvider in the root file 'App.tsx' then it started throwing error on the startup and currently, I'm using expo ^34.0.1.

### Expected Behavior

ReduxNetworkProvider and all other functionalities working with the latest @react-native-community/netinfo version.

### How to reproduce

_Install the "react-native-offline": "^5.4.0" and "@react-native-community/netinfo": "4.4.0" and wrap your component like:_

```
 <Provider store={store}>
    <PersistGate persistor={persistor}>
        <ReduxNetworkProvider>
          <React.Fragment>       
                <AppNavigator {...{ onNavigationStateChange }} />
          </React.Fragment>
        </ReduxNetworkProvider>
     </PersistGate>
  </Provider>
```

### Your Environment

| software             | version
| ----------------     | -------
| react-native-offline | ^5.4.0"
| expo | ^34.0.1
| @react-native-community/netinfo | 4.4.0
| react | 16.8.3

**Comment by helderburato** [comment]
@imtalwindersingh maybe passing just:

```js
<Provider store={store}>
    <ReduxNetworkProvider>
      <AppNavigator {...{ onNavigationStateChange }} />
    </ReduxNetworkProvider>
  </Provider>
```

If you read [here](https://github.com/rgommezz/react-native-offline#reduxnetworkprovider) has a explanation about.

**Comment by imtalwindersingh** [comment]
@helderburato Yes I tried with this but no success. I think there is some problem with dependency versions.

**Comment by helderburato** [comment]
> @helderburato Yes I tried with this but no success. I think there is some problem with dependency versions.

Just to confirm, what version of `redux-persist` you're using? At the project I'm working the unique version of `redux-persist` worked is the `4.6.0`.

**Comment by helderburato** [comment]
> @helderburato Yes I tried with this but no success. I think there is some problem with dependency versions.

This issue https://github.com/react-native-community/react-native-netinfo/issues/282 is about the problem you're getting.

**Comment by imtalwindersingh** [comment]
Still facing the same issue even with this simpler child component. I think the problem is something else
```
    <Provider store={store}>
        <ReduxNetworkProvider>
          <View>
            <Text>Testing</Text>
          </View>
        </ReduxNetworkProvider>
      </Provider>
```

**Comment by chrisreactnative** [comment]
@imtalwindersingh did you ever manage to solve this?

**Comment by lc3t35** [comment]
Yep, I solved it by removing react-native-offline from my code.
Dependency on react-native-community/netinfo@5.5.1 makes it impossible to work with expo sdk35/36 which relies on react-native-community/netinfo@4.6.0. This seems also to happen with bugsnag : see https://github.com/bugsnag/bugsnag-js/issues/719.

**Comment by 1ike** [comment]
I'm trying to integrate  react-native-offline into my project (with Expo), so I had had install react-native-community/netinfo@4.6.0 and move part of react-native-offline code base associated with netinfo into my code base. So ReduxNetworkProvider and checkInternetConnection I import from my code and the rest -  from react-native-offline.

**Comment by rgommezz** [comment]
Hey guys,

Could you please try the version `5.6.0` and let me know?

I've updated the documentation and relaxed the dependencies, to make it compatible with both RN >= 60 and Expo SDK >=35.

**Comment by 1ike** [comment]
> Could you please try the latest version 5.6.0 

Got error:
```
Unable to resolve "redux-saga" from "node_modules\react-native-offline\dist\react-native-offline.js"
Failed building JavaScript bundle.
```

**Comment by rgommezz** [comment]
Thanks @1ike, I think I've figured out the root cause. I've released `5.6.1`, please do let me know

**Comment by 1ike** [comment]
Now bundle build passed but at start crashed with error:
```
Could not find "store" in the context of "Connect(ReduxNetworkProvider)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(ReduxNetworkProvider) in connect options.
- node_modules\react-native-offline\node_modules\react-redux\lib\components\connectAdvanced.js:258:10 in ConnectFunction
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:10696:17 in renderWithHooks
- ... 9 more stack frames from framework internals

Warning: %s: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI., Ro
otErrorBoundary
- node_modules\expo\build\logs\LogSerialization.js:166:14 in _captureConsoleStackTrace
- node_modules\expo\build\logs\LogSerialization.js:41:24 in serializeLogDataAsync
- ... 9 more stack frames from framework internals
```

**Comment by rgommezz** [comment]
@1ike do you have a version of `react-redux` installed that is higher than 7.0?

**Comment by 1ike** [comment]
@rgommezz  I have 7.0.1.

It's more like [this](https://github.com/rgommezz/react-native-offline/issues/207), the [last comments](https://github.com/rgommezz/react-native-offline/issues/207#issuecomment-590669327) about netinfo.

**Comment by jordenchang55** [comment]
@rgommezz 
I am using`5.6.1` and the issue is still exist.
In addition, I use `NetworkProvider` instead of `ReduxNetworkProvider`.

**Comment by dolsem** [comment]
I have the same problem on netinfo version 5.9.2. Downgrading it to 5.2.0 did not help.

**Comment by chrislawlortech** [comment]
Here is my config which got it working for me:

@react-native-community/netinfo: ^5.6.2

expo: ^35.0.0

Hope this helps! After this delete your yarn.lock and yarn install again. Run expo start -c to clear cache

Sorry for the lack of formatting, thought you might have wanted a quick answer.. this one took me a while to figure out
